### ISSUE TITLE
Improve ML & AI

### ISSUE THREAD

**Issue by CVforty2** [CSE442-Foodsomnia/Foodsomnia_website#15]
Come up with a simpler approach to the ML and AI portion of the project

Test:
Find a paper or program the simple version of the new approach. Define it and write it out as well.

**Comment by jyan7555** [comment]
- Given a set of ingredients, use the spoonacular API to generate possible recipes
- Initially, start off with random suggestions 
    - Simple approach: Use random recommendation only / based on popularity among everyone
- AI approach (rough idea): After X amount of suggestions, shift Y% of suggestions to ML. Repeat until 80% from algorithm and 20% random recommendation
    - ML method will be Unsupervised Learning: K-Means (SKLearn in Python)
    - Cluster based on what the user swiped yes on
- Suggest recipes with ingredients same as the clusters
